trigger: 
  - master

# NOTE: only lowercase alphanumeric characters and hyphens allowed in S3 bucket name
name: $(SourceBranchName)-$(BuildID)-$(Rev:r)-$(Date:yyyy-MM-dd)

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: TestApp
  displayName: Test App
  jobs:
  - template: job-test-app.yml
